FROM obs-browser-base:1.0.0

WORKDIR /obs-browser

COPY ./docker/entry_api.sh /
RUN chmod +x /obs-browser/obs-ui && chmod +x /entry_api.sh

ENV EXECUTEROOT=/obs-browser

ENTRYPOINT ["/entry_api.sh"]

CMD ["start"]
